[gitlab_srv]
gitlab ansible_host=10.30.10.100

[runners]
gitrunner1 ansible_host=10.30.10.101
gitrunner2 ansible_host=10.30.10.102

[all:children]
gitlab_srv
runners

[all:vars]
ansible_user=hyfer
ansible_ssh_private_key_file=~/creds/RedKeys.pem
ansible_python_interpreter=/usr/bin/python3